/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControlePessoa;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Pessoa;

/**
 *
 * @author Leonardo
 */
public class DialogPessoa extends javax.swing.JDialog {
    
    Pessoa pessoa;
    boolean sucessoNaBusca = false;
    String antigoCpf;
    
    /**
     * Creates new form DialogPessoa
     */
    public DialogPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        bloquearCampos();
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFuncionario = new javax.swing.ButtonGroup();
        bgCrudPessoa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbCrudPessoaCadastrar = new javax.swing.JRadioButton();
        rbCrudPessoaBuscar = new javax.swing.JRadioButton();
        rbCrudPessoaAlterar = new javax.swing.JRadioButton();
        rbCrudPessoaExcluir = new javax.swing.JRadioButton();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbCPF = new javax.swing.JLabel();
        btFoto = new javax.swing.JButton();
        pnFoto = new javax.swing.JPanel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        cbAndar = new javax.swing.JComboBox<>();
        lbAndar = new javax.swing.JLabel();
        lbSala = new javax.swing.JLabel();
        cbSala = new javax.swing.JComboBox<>();
        tfHorario = new javax.swing.JFormattedTextField();
        lbHorario = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        lbCartao = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbCartao = new javax.swing.JComboBox<>();
        lbCelular = new javax.swing.JLabel();
        tfCelular = new javax.swing.JFormattedTextField();
        rbFuncionario = new javax.swing.JRadioButton();
        rbVisitante = new javax.swing.JRadioButton();
        btOk = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btLimparCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bgCrudPessoa.add(rbCrudPessoaCadastrar);
        rbCrudPessoaCadastrar.setText("Cadastrar");
        rbCrudPessoaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudPessoaCadastrarActionPerformed(evt);
            }
        });

        bgCrudPessoa.add(rbCrudPessoaBuscar);
        rbCrudPessoaBuscar.setText("buscar");
        rbCrudPessoaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudPessoaBuscarActionPerformed(evt);
            }
        });

        bgCrudPessoa.add(rbCrudPessoaAlterar);
        rbCrudPessoaAlterar.setText("Alterar");
        rbCrudPessoaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudPessoaAlterarActionPerformed(evt);
            }
        });

        bgCrudPessoa.add(rbCrudPessoaExcluir);
        rbCrudPessoaExcluir.setText("Excluir");
        rbCrudPessoaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudPessoaExcluirActionPerformed(evt);
            }
        });

        lbNome.setText("Nome:");

        lbCPF.setText("CPF:");

        btFoto.setText("Adicionar Foto");

        pnFoto.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnFotoLayout = new javax.swing.GroupLayout(pnFoto);
        pnFoto.setLayout(pnFotoLayout);
        pnFotoLayout.setHorizontalGroup(
            pnFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnFotoLayout.setVerticalGroup(
            pnFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbEmail.setText("E-mail:");

        cbAndar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        lbAndar.setText("Andar:");

        lbSala.setText("Sala:");

        cbSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "201", "202", "301", "302", "401", "402" }));

        try {
            tfHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbHorario.setText("Horario:");

        lbCartao.setText("Cartão:");

        cbCartao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        lbCelular.setText("Celular:");

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bgFuncionario.add(rbFuncionario);
        rbFuncionario.setText("Funcionario");

        bgFuncionario.add(rbVisitante);
        rbVisitante.setText("Visitante");

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btLimparCampos.setText("Limpar Campos");
        btLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome)
                            .addComponent(lbCPF))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNome)
                            .addComponent(tfCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCrudPessoaCadastrar)
                        .addGap(69, 69, 69)
                        .addComponent(rbCrudPessoaBuscar)
                        .addGap(77, 77, 77)
                        .addComponent(rbCrudPessoaAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbCrudPessoaExcluir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbEmail)
                                .addGap(18, 18, 18)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbAndar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAndar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfHorario)
                            .addComponent(lbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCartao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbCartao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFuncionario)
                            .addComponent(rbVisitante))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCrudPessoaCadastrar)
                    .addComponent(rbCrudPessoaBuscar)
                    .addComponent(rbCrudPessoaAlterar)
                    .addComponent(rbCrudPessoaExcluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCPF)
                            .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail)))
                    .addComponent(pnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFoto)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCelular)
                        .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAndar)
                        .addGap(16, 16, 16)
                        .addComponent(cbAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(rbFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbVisitante))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHorario)
                            .addComponent(lbCartao))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSala)
                        .addGap(16, 16, 16)
                        .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btVoltar)
                    .addComponent(btLimparCampos))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCrudPessoaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudPessoaCadastrarActionPerformed
        limparCampos();
        liberarCampos();
        btOk.setText("Cadastrar");
    }//GEN-LAST:event_rbCrudPessoaCadastrarActionPerformed

    private void rbCrudPessoaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudPessoaBuscarActionPerformed
        limparCampos();
        bloquearCampos();
        tfCPF.setEnabled(true);
        lbCPF.setEnabled(true);
        btOk.setText("Buscar");
    }//GEN-LAST:event_rbCrudPessoaBuscarActionPerformed

    private void rbCrudPessoaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudPessoaAlterarActionPerformed
        limparCampos();
        bloquearCampos();
        tfCPF.setEnabled(true);
        lbCPF.setEnabled(true);
        btOk.setText("Buscar");

    }//GEN-LAST:event_rbCrudPessoaAlterarActionPerformed

    private void rbCrudPessoaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudPessoaExcluirActionPerformed
        bloquearCampos();
        limparCampos();
        tfCPF.setEnabled(true);
        lbCPF.setEnabled(true);
        btOk.setText("Excluir");
    }//GEN-LAST:event_rbCrudPessoaExcluirActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        int resp;
        if(rbCrudPessoaCadastrar.isSelected()){
            try {
                cadastrarPessoa();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(FramePessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(rbCrudPessoaBuscar.isSelected()){
            try {
                buscarPessoa();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(FramePessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(rbCrudPessoaAlterar.isSelected() && btOk.getText().equals("Buscar")){
            try {
                buscarPessoa();
                           if (sucessoNaBusca){
                                btOk.setText("Alterar");
                                liberarCampos();
                                antigoCpf = tfCPF.getText();
                           }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(DialogPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(rbCrudPessoaAlterar.isSelected() && btOk.getText().equals("Alterar")){
            try {
                alterarPessoa(antigoCpf);
                limparCampos();
                bloquearCampos();
                tfCPF.setEnabled(true);
                btOk.setText("Buscar");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DialogPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            

        }
        else if(rbCrudPessoaExcluir.isSelected()){
            try {
                buscarPessoa();
                if(sucessoNaBusca){
                              resp = JOptionPane.showConfirmDialog(null,"Confirma a exclusão", "Exclusão",JOptionPane.YES_NO_OPTION);
                                if(resp == JOptionPane.YES_OPTION){
                                        excluirPessoa(tfCPF.getText());
                                        limparCampos();
                                    }
                           }
            } catch (SQLException ex) {
                Logger.getLogger(DialogPessoa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DialogPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione alguma das opções!");
        }

    }//GEN-LAST:event_btOkActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogPessoa dialog = new DialogPessoa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
      private void liberarCampos(){
           btFoto.setEnabled(true);
           pnFoto.setEnabled(true);
           cbAndar.setEnabled(true);
           lbAndar.setEnabled(true);
           cbCartao.setEnabled(true);
           lbCartao.setEnabled(true);
           cbSala.setEnabled(true);
           lbSala.setEnabled(true);
           rbFuncionario.setEnabled(true);
           rbVisitante.setEnabled(true);
           tfCelular.setEnabled(true);
           lbCelular.setEnabled(true);
           tfEmail.setEnabled(true);
           lbEmail.setEnabled(true);
           tfHorario.setEnabled(true);
           lbHorario.setEnabled(true);
           tfCPF.setEnabled(true);
           lbCPF.setEnabled(true);
           tfNome.setEnabled(true);
           lbNome.setEnabled(true);
    }
    private void bloquearCampos(){
           btFoto.setEnabled(false);
           pnFoto.setEnabled(false);
           cbAndar.setEnabled(false);
           lbAndar.setEnabled(false);
           cbCartao.setEnabled(false);
           lbCartao.setEnabled(false);
           cbSala.setEnabled(false);
           lbSala.setEnabled(false);
           rbFuncionario.setEnabled(false);
           rbVisitante.setEnabled(false);
           tfCelular.setEnabled(false);
           lbCelular.setEnabled(false);
           tfEmail.setEnabled(false);
           lbEmail.setEnabled(false);
           tfHorario.setEnabled(false);
           lbHorario.setEnabled(false);
           tfCPF.setEnabled(false);
           lbCPF.setEnabled(false);
           tfNome.setEnabled(false);
           lbNome.setEnabled(false);
    }
    private void limparCampos(){
           cbAndar.setSelectedIndex(-1);
           cbSala.setSelectedIndex(-1);
           cbCartao.setSelectedIndex(-1);
           bgFuncionario.clearSelection();
           tfNome.setText("");
           tfCPF.setText("");
           tfEmail.setText("");
           tfCelular.setText("");
           tfHorario.setText("");
    }
    private void cadastrarPessoa() throws SQLException, ClassNotFoundException{
        pessoa = new Pessoa();
        ControlePessoa controlePessoa = new ControlePessoa();
        if(rbFuncionario.isSelected() || rbVisitante.isSelected())
        {
        pessoa.setNome(tfNome.getText());
           pessoa.setEmail(tfEmail.getText());
           pessoa.setAndar((String)cbAndar.getSelectedItem());
           pessoa.setCartao((String)cbCartao.getSelectedItem());
           pessoa.setCelular(tfCelular.getText());
           pessoa.setHorario(tfHorario.getText());
           pessoa.setRg(tfCPF.getText());
           pessoa.setSala((String)cbSala.getSelectedItem());
           pessoa.setTipoPessoa(rbFuncionario.isSelected()?"funcionario": "visitante");
           controlePessoa.InserirPessoa(pessoa);
           limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione o Tipo de Pessoa (Funcionario/Visitante)");
        }
           
    }
    private void buscarPessoa() throws SQLException, ClassNotFoundException
    {
        sucessoNaBusca = false;
        ControlePessoa controlePessoa = new ControlePessoa();
        ResultSet rs;
        
        rs =  controlePessoa.BuscarPessoa(tfCPF.getText());
        
        if (rs.first()){
                    tfNome.setText(rs.getString(1));
                    tfEmail.setText(rs.getString(2));
                    tfCelular.setText(rs.getString(4));
                    cbCartao.addItem(rs.getString(6));
                    cbCartao.setSelectedItem(rs.getString(6));
                    cbAndar.addItem(rs.getString(7));
                    cbAndar.setSelectedItem(rs.getString(7));
                    cbSala.addItem(rs.getString(8));
                    cbSala.setSelectedItem(rs.getString(8));
                    tfHorario.setText(rs.getString(9));
                    switch (rs.getString(5)) 
                    {
                        case "funcionario":
                            rbFuncionario.setSelected(true);
                            break;
                        case "visitante":
                            rbVisitante.setSelected(true);
                            break;
                        default:
                            bgFuncionario.clearSelection();
                            break;
                    }
                    sucessoNaBusca = true;
        }
    }
    private void alterarPessoa(String antigoCpf) throws ClassNotFoundException, SQLException{
        pessoa = new Pessoa();
        ControlePessoa controlePessoa = new ControlePessoa();
        if(rbFuncionario.isSelected() || rbVisitante.isSelected())
        {
        pessoa.setNome(tfNome.getText());
           pessoa.setEmail(tfEmail.getText());
           pessoa.setAndar((String)cbAndar.getSelectedItem());
           pessoa.setCartao((String)cbCartao.getSelectedItem());
           pessoa.setCelular(tfCelular.getText());
           pessoa.setHorario(tfHorario.getText());
           pessoa.setRg(tfCPF.getText());
           pessoa.setSala((String)cbSala.getSelectedItem());
           pessoa.setTipoPessoa(rbFuncionario.isSelected()?"funcionario": "visitante");
           controlePessoa.AlterarPessoa(pessoa,antigoCpf);
           limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione o Tipo de Pessoa (Funcionario/Visitante)");
        }
    }
    private void excluirPessoa(String cpf){
        ControlePessoa controlePessoa = new ControlePessoa();
        
        controlePessoa.ExcluirPessoa(cpf);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCrudPessoa;
    private javax.swing.ButtonGroup bgFuncionario;
    private javax.swing.JButton btFoto;
    private javax.swing.JButton btLimparCampos;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbAndar;
    private javax.swing.JComboBox<String> cbCartao;
    private javax.swing.JComboBox<String> cbSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAndar;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCartao;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHorario;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSala;
    private javax.swing.JPanel pnFoto;
    private javax.swing.JRadioButton rbCrudPessoaAlterar;
    private javax.swing.JRadioButton rbCrudPessoaBuscar;
    private javax.swing.JRadioButton rbCrudPessoaCadastrar;
    private javax.swing.JRadioButton rbCrudPessoaExcluir;
    private javax.swing.JRadioButton rbFuncionario;
    private javax.swing.JRadioButton rbVisitante;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JFormattedTextField tfHorario;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
