/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleEmpresa;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Empresa;


/**
 *
 * @author Leonardo
 */
public class DialogEmpresa extends javax.swing.JDialog {
        Empresa empresa;
        boolean sucessoNaBusca = false;
        String antigoCnpj;
    /**
     * Creates new form DialogEmpresa
     */
    public DialogEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);      
        bloquearCampos();
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEmpresa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbCrudEmpresaCadastrar = new javax.swing.JRadioButton();
        rbCrudEmpresaBuscar = new javax.swing.JRadioButton();
        rbCrudEmpresaAlterar = new javax.swing.JRadioButton();
        rbCrudEmpresaExcluir = new javax.swing.JRadioButton();
        btOk = new javax.swing.JButton();
        btLimparCampos = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbCnpj = new javax.swing.JLabel();
        lbCorrespondente = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbHorarioFuncionamento = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCnpj = new javax.swing.JTextField();
        tfCorrespondente = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        lbAte = new javax.swing.JLabel();
        lbAndar = new javax.swing.JLabel();
        cbAndar = new javax.swing.JComboBox<>();
        lbSala = new javax.swing.JLabel();
        cbSala = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        tfHorarioInicio = new javax.swing.JFormattedTextField();
        tfHorarioFim = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bgEmpresa.add(rbCrudEmpresaCadastrar);
        rbCrudEmpresaCadastrar.setText("Cadastrar");
        rbCrudEmpresaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudEmpresaCadastrarActionPerformed(evt);
            }
        });

        bgEmpresa.add(rbCrudEmpresaBuscar);
        rbCrudEmpresaBuscar.setText("buscar");
        rbCrudEmpresaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudEmpresaBuscarActionPerformed(evt);
            }
        });

        bgEmpresa.add(rbCrudEmpresaAlterar);
        rbCrudEmpresaAlterar.setText("Alterar");
        rbCrudEmpresaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudEmpresaAlterarActionPerformed(evt);
            }
        });

        bgEmpresa.add(rbCrudEmpresaExcluir);
        rbCrudEmpresaExcluir.setText("Excluir");
        rbCrudEmpresaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudEmpresaExcluirActionPerformed(evt);
            }
        });

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btLimparCampos.setText("Limpar Campos");
        btLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        lbNome.setText("Nome:");

        lbCnpj.setText("CNPJ:");

        lbCorrespondente.setText("Correspondente:");

        lbTelefone.setText("Telefone:");

        lbHorarioFuncionamento.setText("Horário de Funcionamento:");

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefoneActionPerformed(evt);
            }
        });

        lbAte.setText("Até as:");

        lbAndar.setText("Andar:");

        cbAndar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        lbSala.setText("Sala:");

        cbSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "201", "202", "301", "302", "401", "402", "501", "502", "601", "602" }));

        try {
            tfHorarioInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfHorarioFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCrudEmpresaCadastrar)
                                    .addComponent(lbNome)
                                    .addComponent(lbCnpj)
                                    .addComponent(lbCorrespondente)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lbTelefone)))
                                .addGap(48, 48, 48))
                            .addComponent(lbHorarioFuncionamento, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCorrespondente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCnpj, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNome))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbAndar, 0, 61, Short.MAX_VALUE)
                                    .addComponent(tfHorarioInicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAte)
                                    .addComponent(lbSala))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbSala, 0, 61, Short.MAX_VALUE)
                                    .addComponent(tfHorarioFim))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCrudEmpresaBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbCrudEmpresaAlterar)
                                .addGap(49, 49, 49)
                                .addComponent(rbCrudEmpresaExcluir)
                                .addGap(14, 14, 14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAndar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCrudEmpresaCadastrar)
                    .addComponent(rbCrudEmpresaBuscar)
                    .addComponent(rbCrudEmpresaAlterar)
                    .addComponent(rbCrudEmpresaExcluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCnpj)
                    .addComponent(tfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCorrespondente)
                    .addComponent(tfCorrespondente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefone)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHorarioFuncionamento)
                    .addComponent(lbAte)
                    .addComponent(tfHorarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHorarioFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAndar)
                    .addComponent(cbAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSala)
                    .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btVoltar)
                    .addComponent(btLimparCampos))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCrudEmpresaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudEmpresaCadastrarActionPerformed
        limparCampos();
        liberarCampos();
        btOk.setText("Cadastrar");
    }//GEN-LAST:event_rbCrudEmpresaCadastrarActionPerformed

    private void rbCrudEmpresaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudEmpresaBuscarActionPerformed
        limparCampos();
        bloquearCampos();
        tfCnpj.setEnabled(true);
        lbCnpj.setEnabled(true);
        btOk.setText("Buscar");
    }//GEN-LAST:event_rbCrudEmpresaBuscarActionPerformed

    private void rbCrudEmpresaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudEmpresaAlterarActionPerformed
        limparCampos();
        bloquearCampos();
        tfCnpj.setEnabled(true);
        lbCnpj.setEnabled(true);
        btOk.setText("Buscar");
    }//GEN-LAST:event_rbCrudEmpresaAlterarActionPerformed

    private void rbCrudEmpresaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudEmpresaExcluirActionPerformed
        bloquearCampos();
        limparCampos();
        tfCnpj.setEnabled(true);
        lbCnpj.setEnabled(true);
        btOk.setText("Excluir");
    }//GEN-LAST:event_rbCrudEmpresaExcluirActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        int resp;
        if(rbCrudEmpresaCadastrar.isSelected()){
            try {
                cadastrarEmpresa();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DialogEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(rbCrudEmpresaBuscar.isSelected()){
            try {
                buscarEmpresa();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(DialogEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(rbCrudEmpresaAlterar.isSelected() && btOk.getText().equals("Buscar")){
            try {
                buscarEmpresa();
                if(sucessoNaBusca){
                    btOk.setText("Alterar");
                    liberarCampos();
                    antigoCnpj = tfCnpj.getText();
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(DialogEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(rbCrudEmpresaAlterar.isSelected() && btOk.getText().equals("Alterar")){
            try {
                alterarEmpresa();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DialogEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            }
            limparCampos();
            bloquearCampos();
            tfCnpj.setEnabled(true);
            btOk.setText("Buscar");
        }
        else if(rbCrudEmpresaExcluir.isSelected()){
            try {
                buscarEmpresa();
                if(sucessoNaBusca){
                resp = JOptionPane.showConfirmDialog(null,"Confirma a exclusão", "Exclusão",JOptionPane.YES_NO_OPTION);
                if(resp == JOptionPane.YES_OPTION){
                    excluirEmpresa();
                    limparCampos();
                }
            }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(DialogEmpresa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione alguma das opções!");
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparCamposActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void tfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEmpresa dialog = new DialogEmpresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
     private void liberarCampos(){
        lbNome.setEnabled(true);
        tfNome.setEnabled(true);
        lbCnpj.setEnabled(true);
        tfCnpj.setEnabled(true);
        lbCorrespondente.setEnabled(true);
        tfCorrespondente.setEnabled(true);
        lbTelefone.setEnabled(true);
        tfTelefone.setEnabled(true);
        lbHorarioFuncionamento.setEnabled(true);
        lbAte.setEnabled(true);
        lbAndar.setEnabled(true);
        lbSala.setEnabled(true);
        cbAndar.setEnabled(true);
        tfHorarioFim.setEnabled(true);
        tfHorarioInicio.setEnabled(true);
        cbSala.setEnabled(true);
        
    }
    private void bloquearCampos(){
        lbNome.setEnabled(false);
        tfNome.setEnabled(false);
        lbCnpj.setEnabled(false);
        tfCnpj.setEnabled(false);
        lbCorrespondente.setEnabled(false);
        tfCorrespondente.setEnabled(false);
        lbTelefone.setEnabled(false);
        tfTelefone.setEnabled(false);
        lbHorarioFuncionamento.setEnabled(false);
        lbAte.setEnabled(false);
        lbAndar.setEnabled(false);
        lbSala.setEnabled(false);
        cbAndar.setEnabled(false);
        tfHorarioFim.setEnabled(false);
        tfHorarioInicio.setEnabled(false);
        cbSala.setEnabled(false);
    }
    private void limparCampos(){
        tfNome.setText("");
        tfCnpj.setText("");
        tfCorrespondente.setText("");
        tfTelefone.setText("");
        cbAndar.setSelectedIndex(-1);
        tfHorarioFim.setText("");
        tfHorarioInicio.setText("");
        cbSala.setSelectedIndex(-1);
                
    }
    private void cadastrarEmpresa() throws ClassNotFoundException, SQLException{
           empresa = new Empresa();
           ControleEmpresa controleEmpresa = new ControleEmpresa();
           empresa.setNome(tfNome.getText());
           empresa.setCnpj(tfCnpj.getText());
           empresa.setCorrespondente(tfCorrespondente.getText());
           empresa.setTelefone(tfTelefone.getText());
           empresa.setAndar((String)cbAndar.getSelectedItem());
           empresa.setHorarioInicio(tfHorarioInicio.getText());
           empresa.setHorarioFim(tfHorarioFim.getText());
           empresa.setSala((String)cbSala.getSelectedItem());
           controleEmpresa.inserirEmpresa(empresa);
           
           limparCampos();
    }
    private void buscarEmpresa() throws SQLException, ClassNotFoundException{
        sucessoNaBusca = false;
        ControleEmpresa controleEmpresa = new ControleEmpresa();
        ResultSet rs;
        
        rs = controleEmpresa.buscarEmpresa(tfCnpj.getText());
        
        if(rs.first()){
                    tfNome.setText(rs.getString(1));
                    tfCnpj.setText(rs.getString(2));
                    tfCorrespondente.setText(rs.getString(3));
                    tfTelefone.setText(rs.getString(4));
                    tfHorarioInicio.setText(rs.getString(5));
                    tfHorarioFim.setText(rs.getString(6));
                    cbAndar.setSelectedItem(rs.getString(7));
                    cbSala.setSelectedItem(rs.getString(8));
                    sucessoNaBusca = true;
            
        }
        
    }
    private void alterarEmpresa() throws ClassNotFoundException, SQLException{
        empresa = new Empresa();
        ControleEmpresa controleEmpresa = new ControleEmpresa();
           empresa.setNome(tfNome.getText());
           empresa.setCnpj(tfCnpj.getText());
           empresa.setCorrespondente(tfCorrespondente.getText());
           empresa.setTelefone(tfTelefone.getText());
           empresa.setAndar((String)cbAndar.getSelectedItem());
           empresa.setHorarioInicio(tfHorarioInicio.getText());
           empresa.setHorarioFim(tfHorarioFim.getText());
           empresa.setSala((String)cbSala.getSelectedItem());
           controleEmpresa.alterarEmpresa(empresa, antigoCnpj);
           limparCampos();
           
    }
    private void excluirEmpresa() throws ClassNotFoundException, SQLException{
        ControleEmpresa controleEmpresa = new ControleEmpresa();
        controleEmpresa.excluirEmpresa(tfCnpj.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEmpresa;
    private javax.swing.JButton btLimparCampos;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbAndar;
    private javax.swing.JComboBox<String> cbSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAndar;
    private javax.swing.JLabel lbAte;
    private javax.swing.JLabel lbCnpj;
    private javax.swing.JLabel lbCorrespondente;
    private javax.swing.JLabel lbHorarioFuncionamento;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSala;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JRadioButton rbCrudEmpresaAlterar;
    private javax.swing.JRadioButton rbCrudEmpresaBuscar;
    private javax.swing.JRadioButton rbCrudEmpresaCadastrar;
    private javax.swing.JRadioButton rbCrudEmpresaExcluir;
    private javax.swing.JTextField tfCnpj;
    private javax.swing.JTextField tfCorrespondente;
    private javax.swing.JFormattedTextField tfHorarioFim;
    private javax.swing.JFormattedTextField tfHorarioInicio;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
