/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.VisitaAgendada;

/**
 *
 * @author aluno
 */
public class FrameVisita extends javax.swing.JFrame {
    static ArrayList<VisitaAgendada> vetVisita;
    VisitaAgendada visita;
    boolean sucessoNaBusca = false;
    /**
     * Creates new form FrameVisita
     */
    public FrameVisita(ArrayList<VisitaAgendada> vetVisita) {
        initComponents();
        this.setLocationRelativeTo(null);
        bloquearCampos();
        limparCampos();
        this.vetVisita = vetVisita;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCrudVisita = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbCrudVisitaCadastrar = new javax.swing.JRadioButton();
        rbCrudVisitaBuscar = new javax.swing.JRadioButton();
        rbCrudVisitaAlterar = new javax.swing.JRadioButton();
        rbCrudVisitaExcluir = new javax.swing.JRadioButton();
        btOk = new javax.swing.JButton();
        btLimparCampos = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbDocumento = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfDocumento = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        lbAndar = new javax.swing.JLabel();
        cbAndar = new javax.swing.JComboBox<>();
        lbSala = new javax.swing.JLabel();
        cbSala = new javax.swing.JComboBox<>();
        lbHorario = new javax.swing.JLabel();
        tfHorario = new javax.swing.JFormattedTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgCrudVisita.add(rbCrudVisitaCadastrar);
        rbCrudVisitaCadastrar.setText("Cadastrar");
        rbCrudVisitaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudVisitaCadastrarActionPerformed(evt);
            }
        });

        bgCrudVisita.add(rbCrudVisitaBuscar);
        rbCrudVisitaBuscar.setText("buscar");
        rbCrudVisitaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudVisitaBuscarActionPerformed(evt);
            }
        });

        bgCrudVisita.add(rbCrudVisitaAlterar);
        rbCrudVisitaAlterar.setText("Alterar");
        rbCrudVisitaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudVisitaAlterarActionPerformed(evt);
            }
        });

        bgCrudVisita.add(rbCrudVisitaExcluir);
        rbCrudVisitaExcluir.setText("Excluir");
        rbCrudVisitaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCrudVisitaExcluirActionPerformed(evt);
            }
        });

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btLimparCampos.setText("Limpar Campos");
        btLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        lbNome.setText("Nome:");

        lbDocumento.setText("CNPJ / CPF:");

        lbEmail.setText("Email:");

        lbTelefone.setText("Telefone:");

        lbAndar.setText("Andar:");

        cbAndar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        lbSala.setText("Sala:");

        cbSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "201", "202", "301", "302", "401", "402" }));

        lbHorario.setText("Horario:");

        try {
            tfHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCrudVisitaCadastrar)
                            .addComponent(lbNome)
                            .addComponent(lbDocumento)
                            .addComponent(lbEmail)
                            .addComponent(lbTelefone))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDocumento)
                            .addComponent(tfNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rbCrudVisitaBuscar)
                                .addGap(77, 77, 77)
                                .addComponent(rbCrudVisitaAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(rbCrudVisitaExcluir))
                            .addComponent(tfEmail)
                            .addComponent(tfTelefone))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbAndar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAndar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfHorario)
                            .addComponent(lbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCrudVisitaCadastrar)
                    .addComponent(rbCrudVisitaBuscar)
                    .addComponent(rbCrudVisitaAlterar)
                    .addComponent(rbCrudVisitaExcluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDocumento)
                    .addComponent(tfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefone)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAndar)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHorario)
                            .addComponent(lbSala))
                        .addGap(16, 16, 16)
                        .addComponent(tfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btLimparCampos)
                    .addComponent(btVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCrudVisitaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudVisitaCadastrarActionPerformed
        limparCampos();
        liberarCampos();
        btOk.setText("Cadastrar");
    }//GEN-LAST:event_rbCrudVisitaCadastrarActionPerformed

    private void rbCrudVisitaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudVisitaBuscarActionPerformed
        limparCampos();
        bloquearCampos();
        tfDocumento.setEnabled(true);
        tfDocumento.setEnabled(true);
        btOk.setText("Buscar");
    }//GEN-LAST:event_rbCrudVisitaBuscarActionPerformed

    private void rbCrudVisitaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudVisitaAlterarActionPerformed
        limparCampos();
        bloquearCampos();
        tfDocumento.setEnabled(true);
        tfDocumento.setEnabled(true);
        btOk.setText("Buscar");
    }//GEN-LAST:event_rbCrudVisitaAlterarActionPerformed

    private void rbCrudVisitaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCrudVisitaExcluirActionPerformed
        bloquearCampos();
        limparCampos();
       tfDocumento.setEnabled(true);
       tfDocumento.setEnabled(true);
       btOk.setText("Excluir");
    }//GEN-LAST:event_rbCrudVisitaExcluirActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        int resp;
        if(rbCrudVisitaCadastrar.isSelected()){
           cadastrarVisita();
       }
       else if(rbCrudVisitaBuscar.isSelected()){
           buscarVisita();
       }
       else if(rbCrudVisitaAlterar.isSelected() && btOk.getText().equals("Buscar")){
           visita = buscarVisita();
           if (visita != null){
                btOk.setText("Alterar");
                liberarCampos();
           }
       }
       else if(rbCrudVisitaAlterar.isSelected() && btOk.getText().equals("Alterar")){
           alterarVisita(visita);
           limparCampos();
           bloquearCampos();
           tfDocumento.setEnabled(true);
           btOk.setText("Buscar");
       }
       else if(rbCrudVisitaExcluir.isSelected()){
           visita = buscarVisita();
           if(visita != null){
              resp = JOptionPane.showConfirmDialog(null,"Confirma a exclusão", "Exclusão",JOptionPane.YES_NO_OPTION);
                if(resp == JOptionPane.YES_OPTION){
                    excluirVisita(visita);
                    limparCampos();
                } 
           }
           
       }
       else{
           JOptionPane.showMessageDialog(null, "Selecione alguma das opções!");
       }
    }//GEN-LAST:event_btOkActionPerformed

    private void btLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparCamposActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVisita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVisita(vetVisita).setVisible(true);
            }
        });
    }
    
    private void liberarCampos(){
        lbNome.setEnabled(true);
        tfNome.setEnabled(true);
        lbDocumento.setEnabled(true);
        tfDocumento.setEnabled(true);
        lbEmail.setEnabled(true);
        tfEmail.setEnabled(true);
        lbTelefone.setEnabled(true);
        tfTelefone.setEnabled(true);
        lbAndar.setEnabled(true);
        lbSala.setEnabled(true);
        cbAndar.setEnabled(true);
        cbSala.setEnabled(true);
        lbHorario.setEnabled(true);
        tfHorario.setEnabled(true);
    }
    private void bloquearCampos(){
        lbNome.setEnabled(false);
        tfNome.setEnabled(false);
        lbDocumento.setEnabled(false);
        tfDocumento.setEnabled(false);
        lbEmail.setEnabled(false);
        tfEmail.setEnabled(false);
        lbTelefone.setEnabled(false);
        tfTelefone.setEnabled(false);
        lbAndar.setEnabled(false);
        lbSala.setEnabled(false);
        cbAndar.setEnabled(false);
        cbSala.setEnabled(false);
        lbHorario.setEnabled(false);
        tfHorario.setEnabled(false);
    }
    private void limparCampos(){
        tfNome.setText("");
        tfDocumento.setText("");
        tfEmail.setText("");
        tfTelefone.setText("");
        cbAndar.setSelectedIndex(-1);
        cbSala.setSelectedIndex(-1);
        tfHorario.setText("");
                
    }
    private void cadastrarVisita(){
        visita = new VisitaAgendada();
        visita.setNome(tfNome.getText());
        visita.setDocumento(tfDocumento.getText());
        visita.setEmail(tfEmail.getText());
        visita.setTelefone(tfTelefone.getText());
        visita.setAndar((String)cbAndar.getSelectedItem());
        visita.setSala((String)cbSala.getSelectedItem());
        visita.setHorario(tfHorario.getText());
        vetVisita.add(visita);
        JOptionPane.showMessageDialog(null, "Cadastro Realizado com sucesso");
           limparCampos();
    }
    private VisitaAgendada buscarVisita(){
        sucessoNaBusca = false;
        if(vetVisita.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não há cadastro de visitas");
        }
        else{
            for(int i = 0; i < vetVisita.size();i++){
                if(tfDocumento.getText().equals(vetVisita.get(i).getDocumento())){
                    tfNome.setText(vetVisita.get(i).getNome());
                    tfEmail.setText(vetVisita.get(i).getEmail());
                    tfTelefone.setText(vetVisita.get(i).getTelefone());
                    cbAndar.setSelectedItem(vetVisita.get(i).getAndar());
                    cbSala.setSelectedItem(vetVisita.get(i).getSala());
                    tfHorario.setText(vetVisita.get(i).getHorario());
                    sucessoNaBusca = true;
                    return vetVisita.get(i);
                }             

            }
            if(!sucessoNaBusca){
                JOptionPane.showMessageDialog(null,"Visita Não Encontrada");
                limparCampos();
            }
        }
        return null;
    }
    private void alterarVisita(VisitaAgendada visita){
        visita.setNome(tfNome.getText());
        visita.setDocumento(tfDocumento.getText());
        visita.setEmail(tfEmail.getText());
        visita.setTelefone(tfTelefone.getText());
        visita.setAndar((String)cbAndar.getSelectedItem());
        visita.setSala((String)cbSala.getSelectedItem());
        visita.setHorario(tfHorario.getText());
        JOptionPane.showMessageDialog(null, "Alterado Com sucesso");
    }
    private void excluirVisita(VisitaAgendada visita){
        vetVisita.remove(visita);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCrudVisita;
    private javax.swing.JButton btLimparCampos;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbAndar;
    private javax.swing.JComboBox<String> cbSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAndar;
    private javax.swing.JLabel lbDocumento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHorario;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSala;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JRadioButton rbCrudVisitaAlterar;
    private javax.swing.JRadioButton rbCrudVisitaBuscar;
    private javax.swing.JRadioButton rbCrudVisitaCadastrar;
    private javax.swing.JRadioButton rbCrudVisitaExcluir;
    private javax.swing.JTextField tfDocumento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JFormattedTextField tfHorario;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
